### PR TITLE
Add Databunker

### PR DESCRIPTION
**Pull request by stremovsky**
Hi

I would like to suggest a new tool to the list - Databunker.
It is an address book on steroids for storing personal data.

More info:
https://databunker.org/
https://databunker.org/files/presentation.pdf

Thanks,
Yuli

### CODE REVIEW

**Comment by jonaschn** [comment]
It is not obvious if this project uses Homomorphic Encryption?
Could you provide some evidence that this tool makes use of HE?

**Comment by jonaschn** [comment]
Feel free to give me some evidence and I will add the tool to the list.
However, I assume that this tool does not use homomorphic encryption.

**Comment by stremovsky** [comment]
Homomorphic Encryption is still not supported.

**Comment by jonaschn** [comment]
Thanks for your reply. Feel free to reopen this PR when HE is supported.

**Pull request closed without merging**
